argocd:
  global:
    domain: "argocd.infra.travel-talk.mkls.space"

  configs:
    params:
      server.insecure: true

  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
      extraTls:
        - hosts:
            - argocd.infra.travel-talk.mkls.space
          secretName: argocd-infra-travel-talk-mkls-space-tls
