---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: travel-talk-dev
spec:
  encryptedData:
    password: AgATwYgUIoaVSsGeVV6F0cxQRQUt2Kxu/2FVOtbJWa/46ap1tnVTfQnBKnv6zh8FfA6qRmCuTG6PeZS47VCSewyUXmaEY8K4MuVNiBxa2n13x/bQfYuubaPAB9zZA/Ye0kBsoKjJrfll6bqGmBy4IlcQLDVqEAa4fIewxlTy0CnXFlJETxBvJTjhNeN4qkpN7GHLWDHlSZglToDBOo1MrPSg6Fgx5K8FHGITw+WVkAB/tBrt5hd3uLB5FEj2OeKTJhsIL8A3hoJnhSg3n/NO5ZOcm8IxjX9K+q8wHdGYPIxNXAn3D3qUFRX2N11cqcxC/h2WQ+cdT2oAdnb3Hqa7Ge3l4Vy82/yS0oHQcdZJPRNN09U8h5WLEkiYwmdk1qLTB+NrLPENYE9h1PjlFgSsnZmbvTBy/2btor4E32suwhC0q/VCSA3g2AssjduvfiT0c5qMQ/tY/r5mjZJuJmm9QOHPRxg7SPZSZG+FfNBVQeptTEOIOQXvmD714FUX34pD6B2nFnNn6SbfUGESoj3WDUD/JYrhoB4F+rMXEgB6RNgh6hQAh7jbScvOxgO3T7R4o7NdK93Whs+fwO1TWdWsgb+ZvE4XNR+wZ0A+SOfxdO+Hg06y5lX4LvRyj+bJ11dGIXpasCTWZUZAUYACq8oQB1PeNWj2P1GYgxy/Le4eZLEjzLVuF24PrQC2Wi6ttipvi5OYHWk8geIkRLQxDQkMZxF9C6kyO2oRZX+E
    postgres-password: AgBuPNzqloTYXAEhItIxpoa+EvF0aFudfPJjV92a9R5TUOH41R8BifX9T+ekNLAYoREg1pOezJ4jjEZJbRBmcjcRHcdaGLG1AQ9ELs3dNrcs/o2OmTmX2EZ/DxX4qwNNUpcUh0nP/UFuL+qUyRI/neBny3ebRpzMhR5DPLEu8SjwrNsKvm0LP4EnTkWAOS/Vhoelwga6YZP14g4ePF4yeG5TbxR1/BYL31SvfUmRkcTlME19wNXDg7MkwuCA3ysW71Rt9OHQLp4zSgJWILLZnQhgRe5kpUrYhE6Lc+wqWP1FqlW1NfzUQwVO+HaiN9IkDKXPInBS/qnu0V9+FcNVFKVRFpeoRF0O/no7Fp2Oa3KeWTTJCcRhkazYhGKwC/2sF3q8b3LOne2hgtdAqWDgz0j2DV8KiUvIFFz+mBLGOrqzxaE0sQZ15PL39WRu484ix3NuYiPxvSEptgGe9JfrOf6XI85tJb9yB7Nb0r5JyqmMwBC8vq2c119h8ZuLwMtW1feUZA993exFkfq6Emx/QQ00YO6Y+3PvZypj1K5KmO/2Yu5fhQQum1PlI7ew2zaJTiNbEHru/oexWUY3+pgECLK/eO+w3ouamt9cRaAG4FhTGruMxqs4Q1V7YJBFlVIEoj+bwjg1rTlznonl+cYweCxR0IL2Wt5s590DSD3/aXhQ1bOymBZTesTFa1W8z5dX4lOcYAV5YBVzR6aY
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: travel-talk-dev
    type: Opaque
